apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jci-bin    # Volume to host Jenkins bin folder
  labels:
    type: dev-bin
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /bin
    server: pvc.com

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cd     # Volume for Storing Deployments
  labels:
    type: dev-cd
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /cd
    server: pvc.com