apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-jci-bin
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  selector:
    matchLabels:
      type: dev-bin
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-cont-deploy
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  selector:
    matchLabels:
      type: dev-cd
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}