apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-jci-home
#  annotations:
#    volume.beta.kubernetes.io/storage-class: standard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 5Gi
  selector:
    matchLabels:
      loc: jci_home
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-jci-cd
#  annotations:
#    volume.beta.kubernetes.io/storage-class: standard

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
       storage: 10Gi
  selector:
    matchLabels:
      loc: jci-cd

