apiVersion: v1
data:
  jenkins-admin-password: UkVWZWFEWnlQWQ==
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: 2019-12-17T11:58:18Z
  labels:
    app.kubernetes.io/component: jenkins-master
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-1.4.1
  name: jenkins
  namespace: default
  resourceVersion: "18281234"
  selfLink: /api/v1/namespaces/default/secrets/jenkins
  uid: 83c2eab0-20c4-11ea-9f62-0aa3971e9b7f
type: Opaque
