apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"gp2"},"parameters":{"fsType":"ext4","type":"gp2"},"provisioner":"kubernetes.io/aws-ebs"}
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: 2019-07-28T11:06:30Z
    name: gp2
    resourceVersion: "208"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2
    uid: c08cf36d-b127-11e9-bd1f-0a6d0a9d8180
  parameters:
    fsType: ext4
    type: gp2
  provisioner: kubernetes.io/aws-ebs
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
